name: "Publish"
on:
  release:
    types:
      - published
      - created
      - released

jobs:
  publish:
    name: Publish released Action to GitHub marketplace
    runs-on: ubuntu-latest
    if: ${{ false }}
    steps:
      - name: Publish action
        uses: technote-space-broken/release-github-actions@v7
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_NAME: '${{ github.actor}}'
          COMMIT_EMAIL: '${{ github.actor}}@pci.com'
          CREATE_MAJOR_VERSION_TAG: true
          CREATE_MINOR_VERSION_TAG: true
          CREATE_PATCH_VERSION_TAG: true
          CLEAN_TARGETS: '.[!.]*,test,src,*.ts,*.json,CHANGELOG.md,_config.yml,.github,coverage,.nyc_output'
          BRANCH_NAME: 'releases/${MAJOR}/${MINOR}/${PATCH}'
        env:
          DEBUG: '*'
